syntax = "proto3";

package app;

import "google/protobuf/timestamp.proto";

option go_package = "Proto/gen/app";

enum Level {
  INFO    = 0;
  WARNING = 1;
  ERROR   = 2;
}

enum ContainerMode {
  Logs  = 0;
  Event = 1;
  Both  = 2;
}

message LogRecord {
  Level                     level = 1;
  string                    code  = 2;
  google.protobuf.Timestamp time  = 3;
  string                    desc  = 4;
}

message EventRecord {
  Level                     level    = 1;
  string                    code     = 2;
  google.protobuf.Timestamp time     = 3;
  string                    metadata = 4;
}

message Record {
  LogRecord   log   = 1;
  EventRecord event = 2;
}